### ISSUE TITLE
demon hunter

### ISSUE THREAD

**Issue by newfriend1** [CuteOne/BadRotations#203] opened 2016-10-28 12:10 UTC
DH interrupt function broken at patch
Some spell ids changed eg: felblade, sigil of flame
Also the the auto swapping between multi and single target is broken all round

**Comment by CuteOne** [comment] 2016-10-28 13:03
This is for Vengeance I take it? Or both?

**Comment by newfriend1** [comment] 2016-10-29 02:59
both specs

**Comment by CuteOne** [comment] 2016-10-30 00:01
Seems to be some issues beyond those mentioned, I will try to resolve these as quickly as possible. Currently working on a commission to develop Guardian profile which is my current priority, I am sorry for the problem and will try to find time to address these.

**Comment by newfriend1** [comment] 2016-10-30 02:45
Much appreciated. As is all the work done on this project.

**Comment by CuteOne** [comment] 2016-11-03 03:39
Sorry for the delay, busy busy, but I fixed the issue with Felblade not working. Let me know how it works for you.

**Comment by leaderquebec** [comment] 2016-11-10 06:42
I play DH vengence and havoc (now work fine with felblade)

**Comment by newfriend1** [comment] 2016-11-12 10:48
updates to core broke vengeance, began with infernal strike removing target, now it does not load at all

**Comment by CuteOne** [comment] 2016-11-12 19:20
I will have Vengeance fixed TODAY, and I apologize for the continued problems with it and thank you for your patience.

**Comment by CuteOne** [comment] 2016-11-13 18:09
Update is up, try out CuteOne for Vengeance and let me know

**Comment by newfriend1** [comment] 2016-11-15 03:25
its amazing! I did change the interrupt sigils placement to work the same as sigil of flame and also changed infernal strike back to the same as the old profile as i couldn't get it to trigger

**Comment by CuteOne** [comment] 2016-11-15 05:19
Thanks, and nothing is out of the question. Would you mind sharing the changes you did?

**Comment by newfriend1** [comment] 2016-11-15 05:32
great!

line 99
`			-- Sigil of Silence
                bb.ui:createCheckbox(section, "Sigil of Silence")`

line 259
`                                if cast.sigilOfSilence("best",false,1,8) then return end`

line 263
`                                if cast.sigilOfMisery("best",false,1,8) then return end`

line 370
`                    if recharge.infernalStrike <= 2 and getDistance("target") < 5 then
                        if cast.infernalStrike("player") then return end
                    end`

**Comment by CuteOne** [comment] 2016-11-15 07:50
Ok just pushed an update fixing both sigil of silence and infernal strike with the code I originally had, there was a different issue causing infernal strike to not work in addition to sigil of misery as an interrupt

**Comment by newfriend1** [comment] 2016-11-16 05:08
still none are working in new push, tested on many different mobs. only interrupt that triggers is consume magic. wish i could help more but i really dont know what im doing lol 
I only try different things and they either work or dont such as above, changed those things and they work but may not be intended to work like that

**Comment by CuteOne** [comment] 2016-11-16 08:58
Pushed another update, see of that changes anything.

**Comment by newfriend1** [comment] 2016-11-17 05:25
All working but using the "best" placement for infernal strike is a bit unpredictable, for movement probably fine or possibly use "thisunit" , but for dps suggested to cast at player. and it uses up both charges leaving none for "emergency situations"

typo that wasn't allowing the check to work for SOM selection in interrupts
line 99
            -- Sigil of Misery
               ` br.ui:createCheckbox(section, "Sigil of Misery - Int")`

**Comment by CuteOne** [comment] 2016-11-17 05:31
Ok so if charges are > 1 then cast at target location instead of best? This would leave 1 for emergency use.

**Comment by newfriend1** [comment] 2016-11-17 06:58
Yes but casting at your characters location, so more or less it doesn't move you, you just get the damage from it

**Comment by CuteOne** [comment] 2016-11-17 07:37
Right that's the same conclusion i came to when testing in a mythic, updates should be out shortly.

**Comment by newfriend1** [comment] 2016-11-18 08:41
perfect except when casing infernal strike it looses target. (i dont have dynamic targeting enabled if this is required for it) 
Also performance wise when entering an area/instance with excessive amounts of mobs there is a drastic load increase resulting in fps performance diminished severely

**Comment by CuteOne** [comment] 2016-11-18 09:13
I am not sure why that is, I have a similar issue with Havoc as well and loosing target. The issue is likely due to the debuff per target tracking I have some ideas on resolving this but it will have to wait until next nightly.

**Comment by newfriend1** [comment] 2016-11-18 10:08
No rush, takes time to correct things, sometimes changes to other things break this or that. This is understood and its coming along great!

**Comment by CuteOne** [comment] 2016-11-19 14:44
Performance should be better now.

**Comment by newfriend1** [comment] 2016-11-19 17:52
seems to stop attacking (only auto attack) waiting for cool downs on abilities instead skipping and using fillers

**Comment by newfriend1** [comment] 2016-11-21 02:38
you're the best! its perfect! 
suggestion:  to add enemy range check for casting infernal strike, just to make sure it hits something. Its not needed but just a suggestion to make it "fool proof"

**Comment by CuteOne** [comment] 2016-11-21 03:27
Already did, just not pushed, and I absolutely hate tanking but because of
you I love Vengeance now :P

**Comment by newfriend1** [comment] 2016-11-24 07:12
Infernal stopped casting again.
I hate tanking too besides prot paladain and DH. Although not perfect (waiting for buffs)  the DH tanking is something different to the others. 
Always good to try something new ;) 

also this 
```
472x ...otations\Demon Hunter\Vengeance\VengeanceCuteOne.lua:357: attempt to index field '?' (a nil value)
...otations\Demon Hunter\Vengeance\VengeanceCuteOne.lua:357: in function `run'
BadRotations\Rotations\cCharacter.lua:292: in function `startRotation'
...ions\Rotations\Demon Hunter\Vengeance\cVengeance.lua:107: in function `update'
...tions\Rotations\Demon Hunter\Vengeance\Vengeance.lua:12: in function `?'
BadRotations\System\Core.lua:326: in function <BadRotations\System\Core.lua:244>
```

tends to happen when opening with throw glaive out of melee range, no idea what it is but may be useful to you

**Comment by Aleksaas** [comment] 2016-11-24 10:02
I now this is not section for it, but I dont know where to write, so you can delete after. Can anyone tell me how safe it is right now, because thre are much bans these days, and because FireHack is detectable now, did anyone here get banned?

**Comment by newfriend1** [comment] 2016-11-24 13:47
its never safe, using the paid and more "popular" unlockers/bots will get you more attention. key is to blend not stand out.

**Comment by newfriend1** [comment] 2016-11-24 13:52
P.S @CuteOne if you hate healing you might want to look at the holy paly they're doing good damage atm. Another thing to destroy things with plus god mode like veng

**Comment by Aleksaas** [comment] 2016-11-24 13:52
But FireHack is the on of the most popular, and u cannot use this without FireHack, that's why I am asking.

**Comment by Aleksaas** [comment] 2016-11-24 13:57
One more question, is there any tutorial how to setup this bot? Which files to copy and where?

**Comment by newfriend1** [comment] 2016-11-24 14:20
You can use FH or EWT (need to use 32 bit wow) for the unlocker. basically you just download and put it in your addon folder, use LUA unlocker and it should work after setting options you want. the front page has brief instructions  on it.

**Comment by CuteOne** [comment] 2016-11-25 01:47
https://github.com/CuteOne/BadRotations/wiki/Installation

**Comment by newfriend1** [comment] 2016-11-29 05:57
FPS thing is back again with many units around, friendly or unfriendly, not as bad as before though.  rest is great!

**Comment by CuteOne** [comment] 2016-11-29 18:20
I do have it adding enemy units within a 20yrd radius to preserve pre-emptive stealthing on Druid and Rogue classes.

**Comment by CuteOne** [comment] 2016-12-13 07:56
Closing

**Closed by CuteOne** 2016-12-13 07:56 UTC
